### ISSUE TITLE
Problem with the compiler

### ISSUE THREAD

**Issue by ta12162** [jzavatoneveth/hhg-test#3]
Hey, sorry to bother but every time I try to run your HHG-test I get this error message back. 
I am unsure where it is coming from as I have a compiler and the Machine Learning and statistics toolbox installed. Let me know if you might know where this is coming from? 
Thanks 
![image](https://user-images.githubusercontent.com/65171116/83775842-56783f80-a67f-11ea-83ae-fa7fbc14de5e.png)

**Comment by ta12162** [comment]
Problem sorted out, sorry for that. Made a silly mistake

**Comment by jzavatoneveth** [comment]
Not a problem! Please let me know if you encounter other issues.
